src/Entity/Annonce.php
<?php

namespace App\Entity;

use App\Repository\AnnonceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AnnonceRepository::class)
 * @ORM\Table(name="annonce", indexes={@ORM\Index(columns={"title"}, flags={"fulltext"})})
 */
class Annonce
{

  const DEVISE = 'eur';

  /**
   * @ORM\Id
   * @ORM\GeneratedValue
   * @ORM\Column(type="integer")
   */
  private $id;

  /**
   * @ORM\Column(type="string", length=255, nullable=true)
   */
  private $description;

  /**
   * @ORM\Column(type="boolean")
   */
  private $shipment;

    /**
   * @ORM\Column(type="boolean")
   */
  private $statutLivraison;

  /**
   * @ORM\Column(type="float")
   */
  private $priceOrigin;

  /**
   * @ORM\Column(type="float")
   */
  private $priceTotal;

  /**
   * @ORM\Column(type="date")
   */
  private $created_at;

  /**
   * @ORM\Column(type="boolean")
   */
  private $plantPot;

  /**
   * @ORM\Column(type="date")
   */
  private $dateExpiration;

  /**
   * @ORM\Column(type="boolean")
   */
  private $sold;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $poids;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $title;

    /**
   * @ORM\Column(type="string", length=255, nullable=true)
   */
  private $token;

  /**
   * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="annonces")
   * @ORM\JoinColumn(nullable=false)
   */
  private $category;

  /**
   * @ORM\OneToMany(targetEntity=Image::class, mappedBy="annonce", orphanRemoval=true, cascade={"persist"})
   */
  private $images;

  /**
   * @ORM\ManyToOne(targetEntity=User::class, inversedBy="annonces")
   * @ORM\JoinColumn(nullable=false)
   */
  private $user;

  /**
   * @ORM\Column(type="string", length=255, nullable=true)
   */
  private $acheteur;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $Ville;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $expAddress;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $expZipCode;

  /**
   * @ORM\Column(type="string", length=255, nullable=true)
   */
  private $expRelId;

  /**
  * @ORM\Column(type="string", length=255, nullable=true)
  */
  private $expNumber;

  /**
  * @ORM\Column(type="string", length=400, nullable=true)
  */
  private $etiquetteURL;

    /**
  * @ORM\Column(type="string", length=400, nullable=true)
  */
  private $Tracing_url;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $status;

  public function getId(): ?int
  {
    return $this->id;
  }

  public function getDescription(): ?string
  {
    return $this->description;
  }

  public function setDescription(?string $description): self
  {
    $this->description = $description;

    return $this;
  }

  public function getShipment(): ?bool
  {
    return $this->shipment;
  }

  public function setShipment(bool $shipment): self
  {
    $this->shipment = $shipment;

    return $this;
  }
  

  public function getStatutLivraison(): ?bool
  {
    return $this->statutLivraison;
  }

  public function setStatutLivraison(bool $statutLivraison): self
  {
    $this->statutLivraison = $statutLivraison;

    return $this;
  }

  public function getPriceOrigin(): ?float
  {
    return $this->priceOrigin;
  }

  public function setPriceOrigin(float $priceOrigin): self
  {
    $this->priceOrigin = $priceOrigin;

    return $this;
  }

  public function getPriceTotal(): ?float
  {
    return $this->priceTotal;
  }

  public function setPriceTotal(float $priceTotal): self
  {
    $this->priceTotal = $priceTotal;

    return $this;
  }

  public function getCreatedAt(): ?\DateTimeInterface
  {
    return $this->created_at;
  }

  public function setCreatedAt(\DateTimeInterface $created_at): self
  {
    $this->created_at = $created_at;

    return $this;
  }

  public function getPlantPot(): ?bool
  {
    return $this->plantPot;
  }

  public function setPlantPot(bool $plantPot): self
  {
    $this->plantPot = $plantPot;

    return $this;
  }

  public function getDateExpiration(): ?\DateTimeInterface
  {
    return $this->dateExpiration;
  }

  public function setDateExpiration(\DateTimeInterface $dateExpiration): self
  {
    $this->dateExpiration = $dateExpiration;

    return $this;
  }

  public function getSold(): ?bool
  {
    return $this->sold;
  }

  public function setSold(bool $sold): self
  {
    $this->sold = $sold;

    return $this;
  }

  public function getPoids(): ?string
  {
    return $this->poids;
  }

  public function setPoids(string $poids): self
  {
    $this->poids = $poids;

    return $this;
  }

  public function getTitle(): ?string
  {
    return $this->title;
  }

  public function setTitle(string $title): self
  {
    $this->title = $title;

    return $this;
  }

  public function getToken(): ?string
  {
    return $this->token;
  }

  public function setToken(string $token): self
  {
    $this->token = $token;

    return $this;
  }

  public function getCategory(): ?Category
  {
    return $this->category;
  }

  public function setCategory(?Category $category): self
  {
    $this->category = $category;

    return $this;
  }

  public function __construct()
  {
    $this->createdAt = new \DateTimeImmutable();
    $this->images = new ArrayCollection();
  }

  /**
   * @return Collection<int, Image>
   */
  public function getImages(): Collection
  {
    return $this->images;
  }

  public function addImage(Image $image): self
  {
    if (!$this->images->contains($image)) {
      $this->images[] = $image;
      $image->setAnnonce($this);
    }

    return $this;
  }

  public function removeImage(Image $image): self
  {
    if ($this->images->removeElement($image)) {
      // set the owning side to null (unless already changed)
      if ($image->getAnnonce() === $this) {
        $image->setAnnonce(null);
      }
    }

    return $this;
  }

  public function getUser(): ?User
  {
    return $this->user;
  }

  public function setUser($user): self
  {
    $this->user = $user;

    return $this;
  }

  public function getAcheteur()
  {
    return $this->acheteur;
  }

  public function setAcheteur($acheteur)
  {
    $this->acheteur = $acheteur;

    return $this;
  }

  public function getVille(): ?string
  {
    return $this->Ville;
  }

  public function setVille(string $Ville): self
  {
    $this->Ville = $Ville;

    return $this;
  }

  public function getExpAddress(): ?string
  {
      return $this->expAddress;
  }

  public function setExpAddress(string $expAddress): self
  {
      $this->expAddress = $expAddress;

      return $this;
  }

  public function getExpZipCode(): ?string
  {
      return $this->expZipCode;
  }

  public function setExpZipCode(string $expZipCode): self
  {
      $this->expZipCode = $expZipCode;

      return $this;
  }

  public function getExpRelId(): ?string
  {
      return $this->expRelId;
  }

  public function setExpRelId(string $expRelId): self
  {
      $this->expRelId = $expRelId;

      return $this;
  }

  public function getExpNumber(): ?string
  {
      return $this->expNumber;
  }

  public function setExpNumber(string $expNumber): self
  {
      $this->expNumber = $expNumber;

      return $this;
  }

  public function getEtiquetteURL(): ?string
  {
      return $this->etiquetteURL;
  }

  public function setEtiquetteURL(string $etiquetteURL): self
  {
      $this->etiquetteURL = $etiquetteURL;

      return $this;
  }

  public function getTracingUrl(): ?string
  {
      return $this->Tracing_url;
  }

  public function setTracingUrl(string $Tracing_url): self
  {
      $this->Tracing_url = $Tracing_url;

      return $this;
  }

  public function getStatus(): ?string
  {
      return $this->status;
  }

  public function setStatus(string $status): self
  {
      $this->status = $status;

      return $this;
  }
}

templates/bundles/bundles/home/annonce.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonce - Plant et Flower{% endblock %}
	{% block javascripts %}
		{{ encore_entry_script_tags("app") }}
		{{ encore_entry_script_tags('annonce') }}
	{% endblock %}
{% block stylesheets %}
	{{ encore_entry_link_tags("app") }}
	{{ encore_entry_link_tags("annonce") }}
{% endblock %}

{% block body %}
	<div class="confirm-popup">
        <div class="inner-popup">
            <p>Êtes-vous sûr de vouloir supprimer l'annonce ?</p>
            <div>
                <div class="popup-oui"><a class="confirm-btn" href="{{ path('delete_annonce' , {'id': annonce.id})}}">Oui</a></div>
                <div class="popup-non"><a class="cancel-btn" href="">Non</a></div>
            </div>
        </div>
    </div>
	<div class="containerAnnonce">
		<button class="return">
			<a href={{ path('app_homepage') }}>Retour</a>
		</button>
		<div class="annonceBody row">
			<div class="imgDes">
					<button class="return2">
						<a href={{ path('app_homepage') }}>Retour</a>
					</button>
					<div class="bigImage">
						<img class="image" id="grand-image"src="{{ asset('/uploads/annonces/' ~ annonce.images[0].name) }}" alt="Grand image"/>
					</div>

					<div class="columnImages col">
						<div class="columnImage">
            			{% if annonce.images|length == 1 %}
						<img class="image mini-image" src="{{ asset('/uploads/annonces/' ~ annonce.images[0].name) }}" alt="Image miniature"/>
							{% endif %}
							{% if annonce.images|length > 1 %}
						<img class="image mini-image" src="{{ asset('/uploads/annonces/' ~ annonce.images[1].name) }}" alt="Image miniature"/>
							{% endif %}
							{% if annonce.images|length > 2 %}
						<img class="image mini-image" src="{{ asset('/uploads/annonces/' ~ annonce.images[2].name) }}" alt="Image miniature"/>
							{% endif %}
						</div>
					</div>
			<div class="bg-gray-global">
				<div class="bg-gray-inactive">
					<div class="headInfo row">
						<div class="green">
							<p>{{category}}</p>
						</div>
						<div class="star"><img src="/img/star.png" alt="Étoile" style="width: 20px;"></div>
					</div>
					<h1 class="plant">{{annonce.title}}</h1>
					<div class="headInfo row">
						<div>
							<h2>{{annonce.ville}}</h2>
						</div>
						<div class="green">
							<span>
								{% if annonce.shipment %}
									Livraison possible
								{% else %}
									Livraison non disponible
								{% endif %}
							</span>
						</div>
					</div>

					<h1 class='priceTotal'>{{annonce.priceTotal}}
						€</h1>
					<div class="headInfo row">
						<p>Date d'expiration : {{annonce.dateExpiration | date('d/m/Y')}}</p>
						{% if annonce.sold %}
							<button class="acheter" style="cursor:pointer" disabled>Déjà vendu</button>
						{% elseif (app.user) and (app.user.id == annonce.user.id) %}
							<button class="delete-btn" style="cursor:pointer">Retirer l'annonce</button>
						{% else %}
							<a href={{ path('payment' , {'id': annonce.id} )}}>

								<button class="acheter" style="cursor:pointer">Acheter</button>
							</a>
						{% endif %}
					</div>
				</div>

			</div>	
				<div class="description">
					<div class="absolute">
							<div class="background">
								<img src="/img/background-yellow-green.png" alt="Background">
							</div>
					</div>
					<div class='titre-description'>
						<h2>Description</h2>
							<p>
								{{ annonce.description }}
								<br><br>
								Pot disponible :
								{% if annonce.plantPot %}
									oui
								{% else %}
									non
								{% endif %}
							</p>
					</div>
				<div id="gray" class="bg-gray-inactive row" style="margin-top: 20px;">
					<div class="profileImage">
						{% if (userAnnonce.image) %}
							<img class="image" src="{{ asset('/uploads/profils/' ~ userAnnonce.image) }}" alt="Photo de profil">

						{% else %}
							<img class="image" src="../img/profil.jpg" alt="Photo de profil default">
						{% endif %}
					</div>
					<div class="profilinfo">
						<h2>{{ prenomauteur }}
							{{nomauteur}}</h2>
						<p style="margin: 5px 0;">Rate</p>
						<div id="toggle-list" class="headInfo row" style="cursor:pointer">
							<h3 style="margin-left:2%">
							{% if annoncesNotSold|length < 2 %}
									{{ annoncesNotSold|length }} Annonce
							{% else %}
									{{ annoncesNotSold|length }} Annonces
							{% endif %}</h3>
							<button class="dropdown-button">
								<img src="/img/down-arrow.png" alt="Étoile" style="width: 20px;"/>
							</button>
						</div>
						<div id="list-annonce" class="col list-annonce inactive">
							{% for annonce in userAnnonce.annonces %}
								{% if annonce.sold == false %}
								<a href={{ path('annonce', {'id': annonce.id}) }}>
									<div class="bg-gray col">
										<div class="row">
											<h4 style="margin: 0;">
												<strong>{{ annonce.title }}</strong>
											</h4>
											<img src="/img/star.png" alt="Étoile" style="width: 25px; height: fit-content;">
										</div>
										<div class="row" style="justify-content: space-between; align-items: center; margin-top: 10px;">
											<h5 style="margin: 0;">{{ annonce.ville }}</h5>
											<p style="background: #C6FFD0; padding: 4px 6px; border-radius: 5px;">
												{% if annonce.shipment %}
													Livraison possible
												{% else %}
													Livraison non disponible
												{% endif %}
											</p>
										</div>
										<div class="row" style="justify-content: space-between; align-items: end;">
											<p>Date d'expiration
												{{ annonce.dateExpiration  | date('d/m/Y') }}</p>
											<h2 style="margin: 0;">{{ annonce.priceTotal }}
												€</h2>
										</div>
									</div>
								</a>
								{% endif %}
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
				<div class="textInfo">
					<p style="font-size: 12px; margin-top: 5px; margin-left: 5px;">Les informations du vendeur seront données seulement après l’achat du produit.</p>
				</div>
		</div>

			</div>
		</div>
	</div>

{% endblock %}

templates/bundles/bundles/home/contact.html.twig
{% extends "base.html.twig" %}

{% block title %}Contact - Plant&Flower{% endblock %}
	{% block javascripts %}
		{{ encore_entry_script_tags("app") }}
	{% endblock %}
{% block stylesheets %}
  {{ encore_entry_link_tags("app") }}
  {{ encore_entry_link_tags("contact") }}
{% endblock %}

{% block body %}
  <div class="main-contact">
    <div class="contact-contact-txt">
      
      <div class="title">
        <h1>Contactez-nous</h1>
        <p>Nous avons à cœur de vous offrir la meilleure expérience possible sur notre site.
          Si vous rencontrez des difficultés avec votre compte ou si vous avez des questions à propos de notre plateforme, n'hésitez pas à nous contacter.</p>
      </div>
      <div>
        <img src="img/contact.png" class="contact-image" alt="Image Contact">
      </div>
    </div>
    <div class="contact-contact-form">
      <div class="message">
        <h3 style="text-align: center; color: #48945d; margin-bottom: 20px">Envoyez-nous un message</h3>

        {{ form_start(form) }}
          {{ form_row(form.name) }}
          {{ form_row(form.email) }}
          {{ form_row(form.subject) }}
          {{ form_row(form.message) }}
          {{ form_row(form.captcha) }} 
          {# must be the same name of this put on the FormBuilder #}
          {{ form_errors(form.captcha) }}
          {# That will display the error of the captcha to user #}
          {{ form_row(form.send) }}
        <p style="text-align: center; color: #48945d; margin-bottom: 10px">{{ message }}</p>

        {{ form_end(form) }}
        
        {# <form class="col input-message-contact">
          <input type="text" placeholder="Nom et prénom" />
          <input type="text" placeholder="Email" />
          <input type="text" placeholder="Objet" />
          <textarea wrap placeholder="Message"></textarea>
          <button>Envoyer</button>
        </form> #}
      </div>
    </div>
  </div>
{% endblock %}

templates/bundles/bundles/home/createAnnonce.html.twig
{% extends "base.html.twig" %} 

{% block title %}Création d'une annonce - Plant&Flower{% endblock %} 
	{% block javascripts %}
		{{ encore_entry_script_tags("app") }}
    {{ encore_entry_script_tags("createAnnonce") }}
	{% endblock %}
{% block stylesheets %}
  {{ encore_entry_link_tags("app") }}
  {{ encore_entry_link_tags("createAnnonce") }}
{% endblock %} 


{% block body %}

    {{ form_start(CreateAnnonceForm) }}
      <div class="form">
        <div class="form_left">
          <div class="add_images">
            {{ form_row(CreateAnnonceForm.images, {
                'label': '+ Ajoutez vos photos',
                'attr': {
                  'class': 'input',
                },
                'id': "get-file"
            })}}
          </div>
          
          <div class="add_images_txt">
            Ajouter jusqu'à 3 photos. (1 photo minimum est obligatoire pour vendre
            votre végétal)
          </div>
          <div class="imageAnnonceContainer">
						<div class="preview-container">
							<img class="image previmage" src="" height="100" width="100"/>
						</div>
            <div class="preview-container">
							<img class="image previmage" src="" height="100" width="100"/>
						</div>
            <div class="preview-container">
							<img class="image previmage" src="" height="100" width="100"/>
						</div>
					</div>
          {% if not CreateAnnonceForm.vars.valid %}
            <div>
              {{ form_errors(CreateAnnonceForm) }}
            </div>
          {% endif %}

  

      <div class="form_item">
        <h3>Titre</h3>
        {{ form_row(CreateAnnonceForm.title, {
          'label': false,
          'attr': {
            'class': 'input',
            'placeholder': 'ex. Orchidée',
          }
        })}}
      </div>
      <div class="form_item">
        <h3>Catégorie</h3>
        {{ form_row(CreateAnnonceForm.category, {
          'label': false,
          'placeholder': 'Choisissez votre catégorie',
          'attr': { 
            'class': 'input',
          }
        })}}
      </div>

      <div class="form_item">
        <h3>Décrivez votre végétal (facultatif)</h3>
        {{ form_row(CreateAnnonceForm.description, {
          'label': false,
          'attr': {
            'class': 'input',
            'placeholder': 'ex. cactus en bonne état',
          }
        })}}
      </div>
            <div class="form_item checkAnnonce">
        {{form_row(CreateAnnonceForm.plantPot,{
          'label': 'Pot disponible',
          'attr': {
            'class': 'checkboxAnnonce',
          }
        })}}
      </div>
      <div class="form_item">
        <h3>Poids du végétal:</h3>
        {{form_row(CreateAnnonceForm.poids, {
          'label': false,
          'attr': {
            'class': 'input',
            }
        })}}
      </div>
    </div>

    <div class="form_right">

      <div class="form_item">
        <h3>Date d'expiration</h3>
        {{form_row(CreateAnnonceForm.dateExpiration, {
          'label': false,
          'attr': {
            'class': 'input',
          }
        })}}
      </div>

      <div class="form_item">
        <h3>Prix</h3>
        {{form_row(CreateAnnonceForm.priceOrigin, {
          'label': false,
          'id': 'first',
          'attr': {
            'class': 'input',
            'placeholder': 'ex. 2,50',
          }
        })}}
        <div id="message"></div>
      </div>
       <div class="form_item">
        <h3>Prix définitif</h3>
        <div class="price" id="result">€</div>
      </div>

      <div class="form_item">
        <p>
          <em>Pour que le site reste gratuit, nous appliquons des frais de commission qui servent à financer la maintenance du service (hébergement, domaines, équipes, matériel...).</em>
        </p>
      </div>

      <div class="form_item livraisonAnnonce">
      <div class='checkAnnonce'>
        {{form_row(CreateAnnonceForm.shipment,{
          'label': 'Livraison possible',
          'attr': {
            'class': 'checkboxAnnonce',
          }
          })}}
        </div>
        <div class="modeRemise">
			<h4>Mode de remise de votre colis</h4>
			<div class="modeFlex">
				<input type="radio"  name="mode" id="remise" class="input checked active" checked>
				<i class="fa-solid fa-handshake icon"></i>
				<p class="mode">Remise en main propre</p>
			</div>

			<div class="modeFlex">
				<input type="radio"  name="mode" id="mode"  class="input checked" >
				<img class="mondial" src="/img/mondialRelay.png" alt="Logo Mondial Relay" ></img>
					<p class="mode">Mondial Relay</p>			
			</div>

			<div class="contenu-widget">
				<div class="mondial_widget" id="Zone_Widget"></div>
					<div>
						<input type="hidden" id="ParcelShopCode" name="ParcelShopCode" />
					</div>
			</div>
		</div>
    <div class="adressExp">
      <div class="form_item villeExpedition">
        <h3>Ville</h3>
        {{form_row(CreateAnnonceForm.ville, {
          'label': false,
          'attr': {
            'class': 'input',
            'placeholder': 'ex. Paris',
          }
        })}}
      </div>
      <div class="form_item">
        {{ form_row(CreateAnnonceForm.expAddress, {
          'label': false,
          'attr': {
            'class': 'input',
            'placeholder': 'Adresse',
          }
        })}}
      </div>
      <div class="form_item">
        {{ form_row(CreateAnnonceForm.expZipCode, {
          'label': false,
          'attr': {
            'class': 'input',
            'placeholder': 'Code Postal',
          }
        })}}
      </div>
    </div>
      </div>

      <div class="form_item">
        <button type="submit">+ AJOUTER</button>
      </div>
    </div>
  </div>
    {{ form_end(CreateAnnonceForm) }}
		<div id="Zone_Widget"></div>
    <input type="hidden" id="expRelId"/>
  </div>

</div>


{% endblock %}

templates/bundles/bundles/home/editAnnonce.html.twig
{% extends "base.html.twig" %} 

{% block title %}Modification d'une annonce - Plant&Flower{% endblock %} 

{% block javascripts %}
	{{ encore_entry_script_tags("app") }}
    {{ encore_entry_script_tags("editAnnonce") }}
{% endblock %}
{% block stylesheets %}
  {{ encore_entry_link_tags("app") }}
  {{ encore_entry_link_tags("createAnnonce") }}
{% endblock %}

{% block body %}

<h1>Modification</h1>

{{ form_start(form) }}
      <div class="form">
        <div class="form_left">
          <div class="add_images">
            {{ form_row(form.images, {
                'label': '+ Ajoutez vos photos',
                'attr': {
                  'class': 'input',
                },
                'id': "get-file"
            })}}
          </div>
          
          <div class="add_images_txt">
            Ajouter jusqu'à 3 photos. (1 photo minimum est obligatoire pour vendre
            votre végétal)
          </div>
          <div class="imageAnnonceContainer">
						<div class="preview-container">
							<img class="image previmageEdit" src="{{ asset('/uploads/annonces/' ~ images[0].name) }}"/>
						</div>
            <div class="preview-container">
            {% if images|length > 1 %}
							<img class="image previmageEdit" src="{{ asset('/uploads/annonces/' ~ images[1].name) }}"/>
            {% else %}
							<img class="image previmageEdit" src="" style='display : none'/>
            {% endif %}
						</div>
            <div class="preview-container">
						{% if images|length > 2 %}
							<img class="image previmageEdit" src="{{ asset('/uploads/annonces/' ~ images[2].name) }}"/>
            {% else %}
							<img class="image previmageEdit" src="" style='display : none'/>
            {% endif %}
						</div>
					</div>
          {% if not form.vars.valid %}
            <div>
              {{ form_errors(form) }}
            </div>
          {% endif %}

  

      <div class="form_item">
        <h3>Titre</h3>
        {{ form_row(form.title, {
          'label': false,
          'attr': {
            'class': 'input',
            'placeholder': 'ex. Orchidée',
          }
        })}}
      </div>

	
      <div class="form_item">
        <h3>Catégorie</h3>
        {{ form_row(form.category, {
          'label': false,
          'placeholder': 'Choisissez votre catégorie',
          'attr': { 
            'class': 'input',
          }
        })}}
      </div>

      <div class="form_item">
        <h3>Décrivez votre végétal (facultatif)</h3>
        {{ form_row(form.description, {
          'label': false,
          'attr': {
            'class': 'input',
            'placeholder': 'ex. cactus en bonne état',
          }
        })}}
      </div>
      <div class="form_item checkAnnonce">
        {{form_row(form.plantPot,{
          'label': 'Pot disponible',
          'attr': {
            'class': 'checkboxAnnonce',
          }
        })}}
      </div>
      <div class="form_item">
        <h3>Poids du végétal:</h3>
        {{form_row(form.poids, {
          'label': false,
          'attr': {
            'class': 'input',
            }
        })}}
      </div>
    </div>

    <div class="form_right">

      <div class="form_item">
        <h3>Date d'expiration</h3>
        {{form_row(form.dateExpiration, {
          'label': false,
          'attr': {
            'class': 'input',
          }
        })}}
      </div>

      <div class="form_item">
        <h3>Prix</h3>
        {{form_row(form.priceOrigin, {
          'label': false,
          'id': 'first',
          'attr': {
            'class': 'input',
            'placeholder': 'ex. 2,50',
          }
        })}}
        <div id="message"></div>
      </div>
       <div class="form_item">
        <h3>Prix définitif</h3>
        <div class="price" id="result">€</div>
      </div>

      <div class="form_item">
        <p>
          <em>Pour que le site reste gratuit, nous appliquons à l'acheteur un frais de service</em>
        </p>
      </div>
      <div class="form_item livraisonAnnonce">
      <div class='checkAnnonce'>
        {{form_row(form.shipment,{
          'label': 'Livraison possible',
          'attr': {
            'class': 'checkboxAnnonce',
          }
          })}}
        </div>
        	<div class="modeRemise">
			<h4>Mode de remise de votre colis</h4>
			<div class="modeFlex">
				<input type="radio"  name="mode" id="remise" class="input checked active" checked>
				<i class="fa-solid fa-handshake icon"></i>
				<p class="mode">Remise en main propre</p>
			</div>

			<div class="modeFlex">
				<input type="radio"  name="mode" id="mode"  class="input checked" >
				<img class="mondial" src="/img/mondialRelay.png" alt="Logo Mondial Relay" ></img>
					<p class="mode">Mondial Relay</p>			
			</div>

			<div class="contenu-widget">
				<div class="mondial_widget" id="Zone_Widget"></div>
					<div>
						<input type="hidden" id="ParcelShopCode" name="ParcelShopCode" />
					</div>
			</div>
		</div>
    <div class="adressExp">
      <div class="form_item villeExpedition">
        <h3>Ville</h3>
        {{form_row(form.ville, {
          'label': false,
          'attr': {
            'class': 'input',
            'placeholder': 'ex. Paris',
          }
        })}}
      </div>
      <div class="form_item">
        {{ form_row(form.expAddress, {
          'label': false,
          'attr': {
            'class': 'input',
            'placeholder': 'Adresse',
          }
        })}}
      </div>
      <div class="form_item">
        {{ form_row(form.expZipCode, {
          'label': false,
          'attr': {
            'class': 'input',
            'placeholder': 'Code Postal',
          }
        })}}
      </div>
    </div>
      </div>

      <div class="form_item">
        <button type="submit">MODIFIER</button>
      </div>
    </div>
  </div>
    {{ form_end(form) }}
		<div id="Zone_Widget"></div>
    <input type="hidden" id="expRelId"/>
  </div>
</div>

{% endblock %}

templates/bundles/bundles/home/sellConfirmationRedirection.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
	{{ encore_entry_link_tags("app") }}
	{{ encore_entry_link_tags("redirectionPayment") }}
{% endblock %}

{% block javascripts %}
  {{ encore_entry_script_tags("app") }}
  {{ encore_entry_script_tags("redirectionPayment") }}
{% endblock %}

{% block body %}
  <div class="redirection-content">
    <h1>Redirection...</h1>
    <div class="loader-container">
      <div class="dot d1"></div>
      <div class="dot d2"></div>
      <div class="dot d3"></div>
    </div>
  </div>
{% endblock %}